// ui/src/lib/components/vms/VmConsole.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { Terminal } from 'xterm';
	import { FitAddon } from 'xterm-addon-fit';
	import 'xterm/css/xterm.css';
	import { PlugZap, Unplug, Copy, Check, Download } from 'lucide-svelte';

	interface Props {
		vmId: string;
		consoleUrl: string;
		getConsoleUrl?: () => Promise<string>;
	}

	let { vmId, consoleUrl, getConsoleUrl }: Props = $props();

	let terminalEl: HTMLDivElement;
	let terminal: Terminal;
	let fitAddon: FitAddon;
	let socket: WebSocket;
	let connected = $state(false);
	let statusText = $state('Disconnected');
	let copied = $state(false);
	let copyTimer: ReturnType<typeof setTimeout>;

	function buildWsUrl(url: string): string {
		return url.startsWith('ws')
			? url
			: `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}${url}`;
	}

	function connectWith(url: string) {
		if (socket) socket.close();
		const wsUrl = buildWsUrl(url);
		socket = new WebSocket(wsUrl);
		socket.binaryType = 'arraybuffer';

		socket.onopen = () => {
			connected = true;
			statusText = 'Connected';
			terminal.writeln('\r\n\x1b[32m[Connected to serial console]\x1b[0m\r\n');
		};

		socket.onmessage = (event) => {
			if (event.data instanceof ArrayBuffer) {
				const data = new Uint8Array(event.data);
				terminal.write(data);
			}
		};

		socket.onclose = () => {
			connected = false;
			statusText = 'Disconnected';
			terminal.writeln('\r\n\x1b[31m[Disconnected]\x1b[0m');
			// No auto-reconnect: user controls reconnection explicitly
		};

		socket.onerror = () => {
			connected = false;
			statusText = 'Disconnected';
			terminal.writeln('\r\n\x1b[31m[Connection error]\x1b[0m');
		};
	}

	async function handleReconnect() {
		let urlToUse = consoleUrl;

		if (getConsoleUrl) {
			statusText = 'Refreshing token...';
			try {
				urlToUse = await getConsoleUrl();
			} catch {
				terminal.writeln('\r\n\x1b[33m[Token refresh failed, retrying with existing URL]\x1b[0m');
				urlToUse = consoleUrl;
			}
		}

		connectWith(urlToUse);
	}

	function handleDisconnect() {
		if (socket) {
			socket.onclose = () => {
				connected = false;
				statusText = 'Disconnected';
				terminal.writeln('\r\n\x1b[31m[Disconnected]\x1b[0m');
			};
			socket.close();
		}
	}

	function getTerminalContent(): string {
		const buffer = terminal.buffer.active;
		const lines: string[] = [];
		for (let i = 0; i < buffer.length; i++) {
			const line = buffer.getLine(i);
			if (line) lines.push(line.translateToString(true));
		}
		return lines.join('\n');
	}

	async function handleCopy() {
		const text = getTerminalContent();
		try {
			await navigator.clipboard.writeText(text);
			copied = true;
			clearTimeout(copyTimer);
			copyTimer = setTimeout(() => {
				copied = false;
			}, 2000);
		} catch {
			terminal.writeln('\r\n\x1b[33m[Copy failed: clipboard not available]\x1b[0m');
		}
	}

	function handleDownload() {
		const text = getTerminalContent();
		const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
		const filename = `console-${vmId}-${timestamp}.txt`;
		const blob = new Blob([text], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		a.click();
		URL.revokeObjectURL(url);
	}

	onMount(() => {
		terminal = new Terminal({
			cursorBlink: true,
			fontSize: 14,
			fontFamily: 'monospace',
			allowProposedApi: true
		});
		fitAddon = new FitAddon();
		terminal.loadAddon(fitAddon);
		terminal.open(terminalEl);
		fitAddon.fit();

		terminal.onData((data) => {
			if (socket?.readyState === WebSocket.OPEN) {
				socket.send(data);
			}
		});

		terminal.onResize(({ cols, rows }) => {
			if (socket?.readyState === WebSocket.OPEN) {
				socket.send(JSON.stringify({ cols, rows }));
			}
		});

		connectWith(consoleUrl);
	});

	onDestroy(() => {
		clearTimeout(copyTimer);
		socket?.close();
		terminal?.dispose();
	});
</script>

<div class="console-wrapper">
	<div class="console-toolbar">
		<div class="toolbar-left">
			<span class="console-status">
				<span class="status-dot" class:connected></span>
				{statusText}
			</span>
			<span class="console-meta">VM {vmId}</span>
		</div>
		<div class="toolbar-right">
			<button
				class="toolbar-btn"
				title="Copy terminal contents"
				onclick={handleCopy}
			>
				{#if copied}
					<Check size={14} />
				{:else}
					<Copy size={14} />
				{/if}
			</button>
			<button
				class="toolbar-btn"
				title="Download terminal contents"
				onclick={handleDownload}
			>
				<Download size={14} />
			</button>
			{#if statusText !== 'Refreshing token...'}
				{#if connected}
					<button
						class="toolbar-btn"
						title="Disconnect"
						onclick={handleDisconnect}
					>
						<Unplug size={14} />
					</button>
				{:else}
					<button
						class="toolbar-btn"
						title="Reconnect"
						onclick={handleReconnect}
					>
						<PlugZap size={14} />
					</button>
				{/if}
			{/if}
		</div>
	</div>
	<div bind:this={terminalEl} class="terminal-container"></div>
</div>

<style>
	.console-wrapper {
		width: 100%;
		background: var(--shell-surface, #1a1a1a);
		border-radius: 8px;
		border: 1px solid var(--shell-line, #333);
		overflow: hidden;
	}

	.console-toolbar {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 0.5rem 0.75rem;
		background: var(--shell-surface-raised, #252525);
		border-bottom: 1px solid var(--shell-line, #333);
		font-size: 0.8rem;
	}

	.toolbar-left {
		display: flex;
		align-items: center;
		gap: 0.75rem;
	}

	.toolbar-right {
		display: flex;
		align-items: center;
		gap: 0.25rem;
	}

	.console-status {
		display: flex;
		align-items: center;
		gap: 0.4rem;
		color: var(--shell-text-secondary, #aaa);
	}

	.status-dot {
		width: 8px;
		height: 8px;
		border-radius: 50%;
		background: #ef4444;
	}

	.status-dot.connected {
		background: #22c55e;
	}

	.console-meta {
		color: var(--shell-text-muted, #888);
		font-family: monospace;
	}

	.toolbar-btn {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 28px;
		height: 28px;
		padding: 0;
		background: transparent;
		border: none;
		border-radius: 4px;
		color: var(--shell-text-secondary, #aaa);
		cursor: pointer;
		transition: background 0.15s ease;
	}

	.toolbar-btn:hover {
		background: var(--shell-surface-hover, rgba(255, 255, 255, 0.08));
		color: var(--shell-text-primary, #ddd);
	}

	.terminal-container {
		width: 100%;
		height: 500px;
		padding: 8px;
	}

	:global(.xterm) {
		height: 100%;
	}

	:global(.xterm-screen) {
		background: transparent !important;
	}
</style>

// chv-ui/src/components/VMConsole.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import '@xterm/xterm/css/xterm.css'
import Dialog from 'primevue/dialog'
import Button from 'primevue/button'
import { useToast } from 'primevue/usetoast'

const props = defineProps<{
  vmId: string
  visible: boolean
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

const toast = useToast()

// Template refs
const terminal = ref<HTMLElement>()

// Terminal and WebSocket state
let xterm: Terminal | null = null
let fitAddon: FitAddon | null = null
let ws: WebSocket | null = null

// Connection status: 'disconnected' | 'connecting' | 'connected' | 'error'
const connectionStatus = ref<'disconnected' | 'connecting' | 'connected' | 'error'>('disconnected')

// WebSocket URL construction
const getWebSocketUrl = (): string => {
  const API_BASE_URL = import.meta.env.VITE_API_URL || window.location.origin
  const token = localStorage.getItem('chv_token') || ''
  
  // Convert http/https to ws/wss
  let wsUrl = API_BASE_URL.replace(/^http/, 'ws')
  if (!wsUrl) {
    wsUrl = `ws://${window.location.host}`
  }
  
  return `${wsUrl}/api/v1/vms/${props.vmId}/console?token=${encodeURIComponent(token)}`
}

// Initialize xterm.js terminal
const initTerminal = () => {
  if (!terminal.value || xterm) return

  xterm = new Terminal({
    theme: {
      background: '#000000',
      foreground: '#00ff00',
      cursor: '#00ff00',
      selectionBackground: '#00ff00',
      selectionForeground: '#000000'
    },
    fontFamily: 'monospace',
    fontSize: 14,
    cursorBlink: true,
    cursorStyle: 'block'
  })

  fitAddon = new FitAddon()
  xterm.loadAddon(fitAddon)

  xterm.open(terminal.value)
  fitAddon.fit()

  // Handle user input - encode and send via WebSocket
  xterm.onData((data: string) => {
    if (ws?.readyState === WebSocket.OPEN) {
      const encoded = btoa(data)
      ws.send(JSON.stringify({
        type: 'input',
        data: encoded
      }))
    }
  })

  // Handle resize events
  window.addEventListener('resize', handleResize)
}

// Handle terminal resize
const handleResize = () => {
  if (fitAddon) {
    try {
      fitAddon.fit()
    } catch (e) {
      // Ignore fit errors
    }
  }
}

// Connect to WebSocket
const connect = () => {
  if (ws) {
    ws.close()
    ws = null
  }

  connectionStatus.value = 'connecting'

  try {
    const url = getWebSocketUrl()
    ws = new WebSocket(url)

    ws.onopen = () => {
      connectionStatus.value = 'connected'
      toast.add({
        severity: 'success',
        summary: 'Connected',
        detail: 'Console connection established',
        life: 3000
      })
    }

    ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data)
        
        switch (msg.type) {
          case 'output':
            // Decode base64 output and write to terminal
            if (msg.data && xterm) {
              const decoded = atob(msg.data)
              xterm.write(decoded)
            }
            break
            
          case 'error':
            // Decode and display error
            if (msg.data) {
              const decoded = atob(msg.data)
              toast.add({
                severity: 'error',
                summary: 'Console Error',
                detail: decoded,
                life: 5000
              })
              if (xterm) {
                xterm.write(`\r\n[ERROR: ${decoded}]\r\n`)
              }
            }
            break
            
          case 'status':
            // Handle status messages
            if (msg.data) {
              const decoded = atob(msg.data)
              if (xterm && decoded !== 'pong') {
                xterm.write(`\r\n[Status: ${decoded}]\r\n`)
              }
            }
            break
            
          case 'input':
            // Echo of input, typically not displayed
            break
            
          default:
            console.warn('Unknown message type:', msg.type)
        }
      } catch (err) {
        console.error('Failed to parse WebSocket message:', err)
      }
    }

    ws.onerror = (error) => {
      console.error('WebSocket error:', error)
      connectionStatus.value = 'error'
      toast.add({
        severity: 'error',
        summary: 'Connection Error',
        detail: 'Failed to connect to VM console',
        life: 5000
      })
    }

    ws.onclose = (event) => {
      if (connectionStatus.value !== 'error') {
        connectionStatus.value = 'disconnected'
      }
      if (xterm) {
        xterm.write('\r\n[Connection closed]\r\n')
      }
    }
  } catch (err) {
    console.error('Failed to create WebSocket:', err)
    connectionStatus.value = 'error'
    toast.add({
      severity: 'error',
      summary: 'Connection Error',
      detail: 'Failed to initialize console connection',
      life: 5000
    })
  }
}

// Disconnect from WebSocket
const disconnect = () => {
  if (ws) {
    ws.close()
    ws = null
  }
  connectionStatus.value = 'disconnected'
}

// Reconnect button handler
const reconnect = () => {
  disconnect()
  if (xterm) {
    xterm.clear()
    xterm.write('[Reconnecting...]\r\n')
  }
  connect()
}

// Watch for visibility changes
watch(() => props.visible, (isVisible) => {
  if (isVisible) {
    nextTick(() => {
      initTerminal()
      connect()
    })
  } else {
    disconnect()
  }
})

// Cleanup on unmount
onUnmounted(() => {
  disconnect()
  window.removeEventListener('resize', handleResize)
  if (xterm) {
    xterm.dispose()
    xterm = null
  }
})

onMounted(() => {
  if (props.visible) {
    nextTick(() => {
      initTerminal()
      connect()
    })
  }
})
</script>

<template>
  <Dialog 
    :visible="visible" 
    @hide="$emit('close')" 
    header="VM Console" 
    maximizable
    :style="{ width: '800px', height: '600px' }"
    :modal="true"
  >
    <div class="console-container">
      <div class="console-toolbar">
        <span :class="['status', connectionStatus]">{{ connectionStatus }}</span>
        <div class="toolbar-actions">
          <Button 
            icon="pi pi-refresh" 
            @click="reconnect" 
            :disabled="connectionStatus === 'connecting'"
            v-tooltip="'Reconnect'"
            text
            severity="secondary"
          />
          <Button 
            icon="pi pi-times" 
            @click="$emit('close')"
            v-tooltip="'Close console'"
            text
            severity="secondary"
          />
        </div>
      </div>
      <div ref="terminal" class="terminal"></div>
    </div>
  </Dialog>
</template>

<style scoped>
.console-container {
  display: flex;
  flex-direction: column;
  height: 500px;
  background: #000000;
  border-radius: 4px;
  overflow: hidden;
}

.console-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  background: #1a1a1a;
  border-bottom: 1px solid #333;
}

.status {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 500;
  text-transform: uppercase;
}

.status::before {
  content: '';
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
}

.status.disconnected::before {
  background: #888;
}

.status.disconnected {
  color: #888;
}

.status.connecting::before {
  background: #ffa500;
  animation: pulse 1s infinite;
}

.status.connecting {
  color: #ffa500;
}

.status.connected::before {
  background: #00ff00;
}

.status.connected {
  color: #00ff00;
}

.status.error::before {
  background: #ff0000;
}

.status.error {
  color: #ff0000;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.toolbar-actions {
  display: flex;
  gap: 4px;
}

.terminal {
  flex: 1;
  padding: 8px;
  overflow: hidden;
}

/* Override xterm styles for better integration */
:deep(.xterm) {
  height: 100%;
}

:deep(.xterm .xterm-viewport) {
  background-color: #000000 !important;
}

:deep(.xterm .xterm-screen) {
  background-color: #000000 !important;
}
</style>
